import "./stats.test.mjs";
import "./search.test.mjs";
import "./collector.test.mjs";
import "./security.test.mjs";
import "./auth.test.mjs";
import "./navigation.test.mjs";
import "./shared-data.test.mjs";
import "./draft.test.mjs";
import "./global-bp.test.mjs";
